name: ArmorstandPlugin
main: tld.sima.armorstand.Main
version: 0.1
author: Simon A
description: A plugin that deals with armorstand interactions
api-version: 1.13
permissions:
  stand:
    description: Allow interaction with armorstand
    permission: armorstand.stand
    permission-message: You don't have the armorstand.stand permission.
  interact:
    description: Allow interaction with armorstand
    permission: stand.interact
    permission: armorstand.interact
    permission-message: You don't have the armorstand.stand permission.
  clone:
    description: When interacting with stand, usually when placing items into it, it returns a copy of the old item and the item placed. This ensures only item that was in place is returned.
    permission: armorstand.clone
    permission-message: You don't have the armorstand.clone permission.
  break:
    description: Allows you to break a stand
    permission: armorstand.break
    permission-message: You don't have the armorstand.break permission.
  smartparenttool:
    description: Allow interaction with armorstand
    permission: armorstand.smartparenttool
    permission-message: You don't have the armorstand.stand permission.
commands:
  atool:
    description: Sets player's custom tool to allow them to mass-alter stands
    usage: /atool <type>
    permission: armorstand.atool
    permission-message: You don't have the armorstand.tool permission.
    